// Generated by scripts/generate-sample-origin-manifest.mjs. Do not edit manually.
// A match establishes byte equality with a committed synthetic sample only.
export const sampleOriginManifest: Readonly<Record<string, string>> = {
  "invoice-buyer-hold.pdf":
    "e79212da09f88dfa244e5a600af044da4068fe84a97e3e3e193846ad9f5e8c32",
  "invoice-clean-match.pdf":
    "cd5516a302262f12ecf186096605bc8f4f5af20f44275e506964685771320385",
  "invoice-po-currency-mismatch.pdf":
    "79271dcaa850d6d2f03eff7dc4e96e4b4a1bc9f574fd38f780a26152ca97609f",
  "invoice-total-mismatch.pdf":
    "4c4b21a76d9363ec2ac918c668bca937560870618ed0c8d47e38e977f283f707",
  "invoice-unreadable-approval.pdf":
    "9506d09cf15ececfe10a3ae6aa80e41a297185d3add354929b63ea8211945df9",
  "warehouse-clean-receipt.pdf":
    "3a0e73e27e367c7116c24913909e4efb73d1cc3200a66ea6fe281a1c7f8bf686",
  "warehouse-item-lot-mismatch.pdf":
    "efec544812940b9db75c93155531fd0cd3f5f1df11fa959be309b455f38c1e9d",
  "warehouse-quantity-correction.pdf":
    "510642d64739db8869f0cfdbc67aa2fc89738f6f4f27a99cbfe9ab7916e3d618",
  "warehouse-quantity-mismatch.pdf":
    "ccccff728ce0c54558e15b7cba557a434a9f78b4dfd7d7d37375135577645506",
  "warehouse-unreadable-damage-note.pdf":
    "e7cbbedd8e7a417956c0d29dbb04ac3ec5eb5546c0862daeeefbb31fd9885c1f",
};
